### ISSUE TITLE
No module named test

### ISSUE THREAD

**Issue by sleighsoft** [andrewf/pcap2har#25]
I am trying to run your program with python 2.7.8 on windows with Babun (cygwin wrapper for windows).
It results in the following error:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from pcap2har import pcap
  File "/cygdrive/c/Users/Julian.Niedermeier/SkyDrive/Studium/HPI-Skripte/Semester_4/Cops & Robbers/SSL-TLS-For-Websecurity/python/pcap2har/pcap2har/pcap.py", line 3, in <module>
    import dpkt
  File "/usr/lib/python2.7/site-packages/dpkt/__init__.py", line 12, in <module>
    import aoe
  File "/usr/lib/python2.7/site-packages/dpkt/aoe.py", line 6, in <module>
    from decorators import deprecated
  File "/usr/lib/python2.7/site-packages/dpkt/decorators.py", line 4, in <module>
    from test import pystone
ImportError: No module named test
```

I have python-test installed and /test is also in my $PYTHONPATH.
Any ideas on how to fix that?

**Comment by andrewf** [comment]
Looks like a dpkt issue. I can't replicate it on my end, but there was a new PyPi version on 11 July. The only thing I can think of is to upgrade dpkt.

Edit: Aha! https://github.com/kbandla/dpkt/issues/199

**Comment by sleighsoft** [comment]
Thanks for digging that up.
So it seems there currently is no fix for my problem other than waiting for it to be solved.

**Comment by andrewf** [comment]
Assuming the latest version on PyPi still doesn't work, you might also try an old release of dpkt from google code https://code.google.com/p/dpkt/downloads/list . pcap2har is really only tested against dpkt 1.7ish (1.8 in the link above should be fine, too, I'm pretty sure I made that release). The section of code that is causing you issues is very new, not in the old project.
