### ISSUE TITLE
No module named 'pcaputil'

### ISSUE THREAD

**Issue by ruokid** [andrewf/pcap2har#31]
I am trying to run your program with python 3.6.0 on Mac and i got this error

```
python main.py ~/Downloads/1.pcap ~/Downloads/1.har

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from pcap2har import pcap
  File "/Users/Imcx/Downloads/pcap2har-master/pcap2har/pcap.py", line 5, in <module>
    from pcaputil import *
ModuleNotFoundError: No module named 'pcaputil'
```

```
pip list
Package    Version
---------- -------
dpkt       1.9.2  
pcappy     0.3    
pip        19.2.3 
pypcap     1.2.3  
setuptools 41.2.0 
wheel      0.33.6
```

**Comment by hm1sty** [comment]
用python2
