### ISSUE TITLE
KeyError: 101

### ISSUE THREAD

**Issue by xingyunjohn1** [andrewf/pcap2har#32]
run `python2 ./main.py 1.pcap 1.har` gets:
```python2 ./main.py 18_11_33_03_29_2022.pcap 1.har
Traceback (most recent call last):
  File "./main.py", line 65, in <module>
    dispatcher = pcap.EasyParsePcap(filename=inputfile)
  File "/mnt/r/pcap2har-master/pcap2har-master/pcap2har/pcap.py", line 80, in EasyParsePcap
    ParsePcap(dispatcher, filename=filename, reader=reader)
  File "/mnt/r/pcap2har-master/pcap2har-master/pcap2har/pcap.py", line 27, in ParsePcap
    pcap = ModifiedReader(f)
  File "/mnt/r/pcap2har-master/pcap2har-master/pcap2har/pcaputil.py", line 122, in __init__
    self.dloff = dpkt.pcap.dltoff[self.__fh.linktype]
KeyError: 101
```

**Comment by sfscgjohnson** [comment]
Getting the Same
